- platform: broadlink
  host: 192.168.1.100
  mac: '34:EA:34:6F:F6:F5'
  friendly_name: Broadlink RM Pro
  type: rm2_home_plus

#### Bedroom TV Switch ####

- platform: template
  switches:
    master_bedroom_tv:
      value_template: "{{ is_state_attr('remote.bedroom', 'current_activity', 'Bedroom TV') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.bedroom
          activity: 'Bedroom TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.bedroom
          activity: 'PowerOff'

#### Family Room TV Switch ####

- platform: template
  switches:
    family_room_tv:
      value_template: "{{ is_state('remote.family_room', 'on') }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.family_room
          activity: 'Watch TV'
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.family_room
          activity: 'PowerOff'