
#### Turns On Pantry Lights When Door Opens ####

- alias: 'Pantry Lights On'
  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.pantry_outlet

#### Turns Off Pantry Lights When Door Close ####

- alias: 'Pantry Lights Off'
  trigger:
    - platform: state
      entity_id: binary_sensor.pantry_door
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.pantry_outlet