
#### Turns On and Off TV Based on Harmony Hub Status ####
  ## Necessary Since Harmony Hub is not near TV ##

- alias: 'Turn off LG TV'
  trigger:
  - platform: state
    entity_id: remote.family_room
    to: 'off'
  action:
  - service: media_player.turn_off
    entity_id: media_player.livingroom_tv

- alias: 'Turn on LG TV'
  trigger:
  - platform: state
    entity_id: remote.family_room
    to: 'on'
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      "mac": "20:3d:bd:62:ff:b8"