- alias: 'Tablet Motion On'
  trigger:
    platform: state
    entity_id: binary_sensor.wall_tablet
    to: 'on'
  action:
  - service: light.turn_on
    data_template:
      entity_id: light.wall_tablet
      brightness: >
        {% if state_attr("sun.sun", "elevation") < 3.5 %}
          75
        {% else %}
          200
        {% endif %}

- alias: 'Tablet Motion Off'
  trigger:
    platform: state
    entity_id: binary_sensor.wall_tablet
    to: 'off'
    for: "00:00:15"
  action:
  - service: light.turn_on
    data:
      entity_id: light.wall_tablet
      brightness: 1

- alias: 'Start Charging'
  trigger:
    platform: numeric_state
    entity_id: binary_sensor.wall_tablet
    value_template: "{{ state.attributes.battery_level }}"
    below: 20
  action:
  - service: switch.turn_on
    entity_id: switch.kitchen_window_decorations

- alias: 'Stop Charging'
  trigger:
    platform: numeric_state
    entity_id: binary_sensor.wall_tablet
    value_template: "{{ state.attributes.battery_level }}"
    above: 80
  action:
  - service: switch.turn_off
    entity_id: switch.kitchen_window_decorations